name: E2E API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout e2e API repo
        uses: actions/checkout@v2
        with: 
          repository: AlejaGonzalezV/Bank-API-Tests
      - name: use node.js 12
        uses: actions/setuup-node@v2
        with:
          node-version: 12.x
      - name: install dependencies
        run: npm ci
      - name: execute e2e API tests
        with: 
          wait-on: "https://bank-users-back.herokuapp.com/users"
          browser: chrome
        run: npm tests

